### ISSUE TITLE
Unable to upload "semgrep.sarif" as it is not valid SARIF

### ISSUE THREAD

**Issue by roisec** [returntocorp/sgrep-action#421] opened 2021-11-08 11:22 UTC
Hi,
I am got this error for the github action:

Run github/codeql-action/upload-sarif@v1
Uploading results
Error details: instance requires property "version"
Error details: instance requires property "runs"
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:

Have any ideas?

**Comment by ievans** [comment] 2021-11-08 16:09
Hi @RoiSec, can you share the SARIF file?

**Comment by ievans** [comment] 2021-11-08 16:09
Probably a dupe of https://github.com/returntocorp/semgrep-action/issues/378

**Comment by roisec** [comment] 2021-11-08 22:17
https://github.com/RoiSec/caspion/runs/4141290747

**Comment by brendongo** [comment] 2021-11-20 00:13
@RoiSec doesnt look like the sarif file is there?

**Comment by brendongo** [comment] 2022-01-27 19:45
I think closed by #457

**Closed as completed by brendongo** 2022-01-27 19:45 UTC
